### PR TITLE
Add traverse

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by sol** [comment]
@basvandijk not sure what the build error is about.  I would try to rerun, but don't have the permissions.

**Comment by sol** [comment]
@basvandijk ping.

**Comment by sol** [comment]
@basvandijk ping

**Comment by basvandijk** [comment]
@sol I send you an invite to become a collaborator. I also added you the the [maintainers on Hackage](http://hackage.haskell.org/package/case-insensitive/maintainers/).

The change LGTM, feel free to merge it yourself.

**Comment by sol** [comment]
I'm investigating the `cassava` build error with GHC 8.2.1.

**Comment by sol** [comment]
Ignoring the build error for now.  I tried to add `--disable-benchmarks` to `.travis.yml` but for some reason the benchmarks were still built.

**Pull request merged**
